---
version: "2"
linters:
  default: all
  disable:
    - depguard
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    - noinlineerr
  settings:
    gosec:
      excludes:
        # Password field in registry auth config is not a secret literal
        - G117
