apiVersion: v2
name: deities
description: A Helm chart for Deities - Kubernetes Image Update Controller
type: application
version: 0.0.0
appVersion: "latest"
keywords:
  - kubernetes
  - controller
  - image
  - registry
  - automation
home: https://github.com/1995parham/deities
sources:
  - https://github.com/1995parham/deities
maintainers:
  - name: 1995parham
    email: parham.alvani@gmail.com
    url: https://github.com/1995parham
